### ISSUE TITLE
Mermaid graphs aren't rendering on website

### ISSUE THREAD

**Issue by smoens** [objectiv/objectiv.io#277]
**Describe the bug**
Mermaid graphs are shown in plain text instead of visualized.
e.g. URL [Objective - Global Contexts](https://objectiv.io/docs/taxonomy/global-contexts/)

**Expected behavior**
Mermaid graph is expected to be rendered

**Screenshots**
![image](https://user-images.githubusercontent.com/1371244/152298052-4fdf7e94-a976-4e44-810f-6f20497c8b2f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 96.0.3

**Comment by ivarpruijn** [comment]
@smoens Thanks for reporting this! We're looking into it. Seems it's related to an overly eager cookie consent that's blocking Mermaid from loading.

**Comment by ivarpruijn** [comment]
@smoens A fix is live now. Thanks again for reporting, and let us know if you run into any issues!
