### ISSUE TITLE
dtype removed from docs of series

### ISSUE THREAD

**Issue by hendrik-obj** [objectiv/objectiv.io#333]
dtype is now entirely gone from reference: series , but also its subclasses don't have it

_Originally posted by @hendrik-obj in https://github.com/objectiv/objectiv.io/pull/331#discussion_r825825977_

**Comment by thijs-obj** [comment]
@hendrik-obj do you have some more context on what is expected that we do under this issue?

**Comment by ivarpruijn** [comment]
As this is now live, I think we can close this issue: https://objectiv.io/docs/modeling/bach/api-reference/Series/dtype/. Please let me know if you disagree @hendrik-obj and we'll re-open this.
